M48
; DRILL file {KiCad (6.0.11)} date Wed Jan  3 20:30:27 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-03T20:30:27+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X65.23Y-86.06
X65.23Y-126.06
X165.23Y-86.06
X165.23Y-126.06
T0
M30
